### ISSUE TITLE
HTML Device Map: Add Enumerations

### ISSUE THREAD

**Issue by marktrayer** [openconnectivityfoundation/devicemodels#10]
I think we need to add one more level with the enums.
e.g. use https://github.com/openconnectivityfoundation/devicemodels/blob/master/oic.enumerationmap-content.json
to list the enums that should be used for a specific device.

**Comment by WAvdBeek** [comment]
https://openconnectivityfoundation.github.io/devicemodels/docs/resource-enum.html
