### ISSUE TITLE
html pages

### ISSUE THREAD

**Issue by WAvdBeek** [openconnectivityfoundation/devicemodels#14]
add link back to the repository for the html page.
e.g. when entering the "html mode" have an button to go back to the readme.md page of the repo

**Comment by WAvdBeek** [comment]
add interpretation of atomic measurements, so that the required and optional fields are also shown in the overview

**Comment by WAvdBeek** [comment]
add logo of OCF to the website

**Comment by marktrayer** [comment]
OCF Logo added as a Link to the OCF home page

**Comment by WAvdBeek** [comment]
- added tabular navigation
- added tab to go back to the github repo
- mark added OCF logo with link
